### ISSUE TITLE
Attribute error with pyqt5 library

### ISSUE THREAD

**Issue by twartzek** [dhatim/python-license-check#21]
Really a nice and helpful tool. Unfortunately if fails for pyqt packages.

> gathering licenses...
Traceback (most recent call last):
...
license = regex_license.search(metadata).group('license')
AttributeError: 'NoneType' object has no attribute 'group'

Reproduce: ini file from repo, requirements.txt with the following content

> PyQt5==5.11.3
PyQt5-sip==4.19.13

**Comment by ochedru** [comment]
For some reason, the license is not present in PyQt5-sip package metadata.
Fixed by https://github.com/dhatim/python-license-check/pull/22.
With the fix, your testcase results in:
```
gathering licenses...
2 packages and dependencies.
check unauthorized packages...
1 package.
    PyQt5 (5.11.3): ['GPL v3']
      dependency:
          PyQt5
check unknown packages...
1 package.
    PyQt5-sip (4.19.13): UNKNOWN
      dependency:
          PyQt5-sip << PyQt5
```

**Comment by twartzek** [comment]
Thanks for the fast response. This fixes indeed the Attribute error. However, I still do not understand your approach with approved packages.

If I write in the ini file

> [Authorized Packages]
PyQt5: 5.11.3
PyQt5-sip: 4.19.13

it still gives me the output (shouldn't it be all ok?):

> gathering licenses...
2 packages and dependencies.
check unauthorized packages...
1 package.
    PyQt5 (5.11.3): ['GPL v3']
      dependency:
          PyQt5
check unknown packages...
1 package.
    PyQt5-sip (4.19.13): UNKNOWN
      dependency:
          PyQt5-sip << PyQt5

I would like to use your tool as a test step in CI pipeline.

**Comment by ochedru** [comment]
Indeed, explicitly authorized packages do not have precedence over authorized licenses. This is a mistake. I am going to fix that.

**Comment by ochedru** [comment]
Fixed by #23 in version 0.3.7
